### ISSUE TITLE
There are two template files for each type

### ISSUE THREAD

**Issue by SethFalco** [Helsinki-NLP/OPUS-ingest#21]
Templates exist in the repo twice, so it's unclear which to use.

* `corpus/template-*` (i.e. `corpus/template-tmx`)
* `templates/*` (i.e. `templates/tmx`)

Based on your recent commit history, it looks like we should be using the latter? (No `Makefile.letsmt`.)

However, could we get confirmation on this? It may be best to get the templates merged so it's in one place, or if one is outdated, just deleted outright.

**Comment by jorgtied** [comment]
Yes, I deleted the old ones now.
